### ISSUE TITLE
Add option to translate invalid characters in hg tag names to valid characters in git tag names

### ISSUE THREAD

**Issue by pabs3** [mnauw/git-remote-hg#44] opened 2021-08-17 07:38 UTC
Forwarding [Debian git-remote-hg#826002](https://bugs.debian.org/826002). When cloning repos that contain tags that contain invalid characters, git-remote-hg prints a warning and then ignores the tag, not creating any corresponding git tags. It would be nice if (optionally) instead the characters that are invalid in git tag names could be translated to valid ones. For example the tilde/~ characters could be translated to underscores. This is most often an issue when cloning repos containing Debian backports, which use the tilde/~ character in their version numbers.

```
$ mkdir hg
$ cd hg
hg $ hg init
hg $ touch foo 
hg $ hg add foo
hg $ hg commit -m foo
hg $ hg tag foo~bar
hg $ hg log
changeset:   1:3f7b12984249
tag:         tip
user:        Paul Wise
date:        Tue Aug 17 15:28:34 2021 +0800
summary:     Added tag foo~bar for changeset 2fe0783478a5

changeset:   0:2fe0783478a5
tag:         foo~bar
user:        Paul Wise
date:        Tue Aug 17 15:28:08 2021 +0800
summary:     foo

hg $ cd ..
$ git clone hg::hg git
Cloning into 'git'...
adding changesets
adding manifests
adding file changes
added 2 changesets with 2 changes to 2 files
new changesets 2fe0783478a5:3f7b12984249
error: * Ignoring funny ref 'refs/tags/foo~bar' locally
progress revision walk 'bookmarks/master' (1/1)
progress revision 0 'master' (0/2)
$ cd git 
git (master=) $ git tag
git (master=) $ 
```

**Comment by mnauw** [comment] 2021-08-21 17:41
The reported version in the referenced bug is very old (0.3-1).  In a recent version, this has been addressed by applying some (form of) URL encoding in 741b440fcc917e6f529491aa641f73f3e032612b.  The resulting tag name is then `foo%7Ebar`, as illustrated by `git log`;
```
commit 3454d18101260894ed37d40e8ea275c91688b8e5 (HEAD -> master, origin/master, origin/branches/default, origin/HEAD)
Author: H G Wells <wells@example.com>
Date:   Sat Aug 21 19:30:40 2021 +0200

    Added tag foo~bar for changeset 6f9b109ae669

Notes (hg):
    d4ab67f33173cabbcb944e4487b9660991028ca6

commit 554032f677994833c9db90499dfdbef0af26e130 (tag: foo%7Ebar)
Author: H G Wells <wells@example.com>
Date:   Sat Aug 21 19:30:32 2021 +0200

    foo

Notes (hg):
    6f9b109ae6699f8d1405e6fbef1041ef98cdb0c4
```
While this looks not as nice as a simple `_` underscore replacement, the transformation should be bidirectional (and a simple underscore replacement cannot be reversed by replacing all those with `~` in general).

**Comment by pabs3** [comment] 2021-08-22 02:37
The initial post in this thread was using the Debian package of v1.0.2.1, which includes commit 741b440 as far as I can tell.

Here is what I get when using the latest commit f5c38f3 instead:

```
$ sudo apt -q purge git-remote-hg
Reading package lists...
Building dependency tree...
Reading state information...
Package 'git-remote-hg' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
$ git clone -q https://github.com/mnauw/git-remote-hg.git
$ cd git-remote-hg/
git-remote-hg (master=) $ git log --oneline | head
f5c38f3 Run Python scripts under the chosen version
git-remote-hg (master=) $ python3 setup.py install --user
running install
running bdist_egg
running egg_info
creating git_remote_hg.egg-info
writing git_remote_hg.egg-info/PKG-INFO
writing dependency_links to git_remote_hg.egg-info/dependency_links.txt
writing top-level names to git_remote_hg.egg-info/top_level.txt
writing manifest file 'git_remote_hg.egg-info/SOURCES.txt'
writing manifest file 'git_remote_hg.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.9
copying and adjusting git-remote-hg -> build/scripts-3.9
copying and adjusting git-hg-helper -> build/scripts-3.9
changing mode of build/scripts-3.9/git-remote-hg from 640 to 755
changing mode of build/scripts-3.9/git-hg-helper from 640 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.9/git-hg-helper -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.9/git-remote-hg -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/git-hg-helper to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/git-remote-hg to 755
copying git_remote_hg.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying git_remote_hg.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying git_remote_hg.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying git_remote_hg.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/git_remote_hg-1.0.2.1-py3.9.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing git_remote_hg-1.0.2.1-py3.9.egg
Copying git_remote_hg-1.0.2.1-py3.9.egg to /home/pabs/.local/lib/python3.9/site-packages
Adding git-remote-hg 1.0.2.1 to easy-install.pth file
Installing git-hg-helper script to /home/pabs/.local/bin
Installing git-remote-hg script to /home/pabs/.local/bin

Installed /home/pabs/.local/lib/python3.9/site-packages/git_remote_hg-1.0.2.1-py3.9.egg
Processing dependencies for git-remote-hg==1.0.2.1
Finished processing dependencies for git-remote-hg==1.0.2.1
git-remote-hg (master %=) $ cd ..
$ mkdir hg
$ cd hg
hg $ hg init
hg $ touch foo
hg $ hg add foo
hg $ hg commit -m foo
hg $ hg tag foo~bar
hg $ hg log
changeset:   1:b671e156ca4e
tag:         tip
user:        Paul Wise <pabs3@bonedaddy.net>
date:        Sun Aug 22 10:21:58 2021 +0800
summary:     Added tag foo~bar for changeset 174183238a41

changeset:   0:174183238a41
tag:         foo~bar
user:        Paul Wise <pabs3@bonedaddy.net>
date:        Sun Aug 22 10:21:55 2021 +0800
summary:     foo

hg $ cd ..
$ export PATH=~/.local/bin/:$PATH
$ git clone hg::hg git
Cloning into 'git'...
adding changesets
adding manifests
adding file changes
added 2 changesets with 2 changes to 2 files
new changesets 174183238a41:b671e156ca4e
error: * Ignoring funny ref 'refs/tags/foo~bar' locally
progress revision walk 'bookmarks/master' (1/1)
progress revision 0 'master' (0/2)
$ cd git 
git (master=) $ git tag
git (master=) $ 
```

**Comment by pabs3** [comment] 2021-08-22 02:40
It looks like the `Ignoring funny ref` error is coming from git itself instead of git-remote-hg:

```
$ git grep -B5 -A9 'Ignoring funny ref'
remote.c-       for (rmp = &ref_map; *rmp; ) {
remote.c-               if ((*rmp)->peer_ref) {
remote.c-                       if (!starts_with((*rmp)->peer_ref->name, "refs/") ||
remote.c-                           check_refname_format((*rmp)->peer_ref->name, 0)) {
remote.c-                               struct ref *ignore = *rmp;
remote.c:                               error("* Ignoring funny ref '%s' locally",
remote.c-                                     (*rmp)->peer_ref->name);
remote.c-                               *rmp = (*rmp)->next;
remote.c-                               free(ignore->peer_ref);
remote.c-                               free(ignore);
remote.c-                               continue;
remote.c-                       }
remote.c-               }
remote.c-               rmp = &((*rmp)->next);
remote.c-       }
```

**Comment by pabs3** [comment] 2021-08-22 02:44
I'm not sure why the translation is working for you but not for me, however I think that for the cases where the git repository is not intended to be bi-directional, but just a one-off conversion to git, where you are leaving the hg repository behind, having an option to use custom transformations, such as to `_`, instead of doing the URL encoding would still be useful.

PS: I have these git/hg versions:

```
$ hg --version | head -n1
Mercurial Distributed SCM (version 5.6.1)
$ git --version 
git version 2.32.0
```

**Comment by mnauw** [comment] 2021-08-22 19:13
The translation of ref names has to be bidirectional because of the way the import works.  First git requests a list of the known refs (in `do_list`), at which stage a transformation is performed to prevent git from seeing "funny refs".  Then git will request to actually fetch those refs, which need to be transformed back to the source name.

It looks like the problem is a change in python; python 3.6 considers `~` reserved and performs URL encoding, whereas python 3.7 no longer considers it reserved.  Rather than coming up with yet-another-way-to-encode, I plan to URL encode "manually" (replace `~` as URL encoding would).

**Comment by pabs3** [comment] 2021-08-23 04:47
That bidirectionality would complicate doing a once-off conversion
indeed, I guess one can always just rename the tags afterwards tho.

That sounds like the right diagnosis as I am using Python 3.9

Thanks.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Closed as completed** 2021-08-28 18:31 UTC
