### ISSUE TITLE
Can't clone

### ISSUE THREAD

**Issue by hasufell** [mnauw/git-remote-hg#20] opened 2018-09-16 14:27 UTC
```
$ git clone "hg::https://bitbucket.org/capitalmatch/webdriver-utils" 3rdparty/webdriver-utils
Cloning into '3rdparty/webdriver-utils'...
requesting all changes
adding changesets
adding manifests
adding file changes
added 124 changesets with 207 changes to 37 files (+1 heads)
new changesets a137b649f934:a8b15525a1cc
progress revision 99 'master' (100/122)
WARNING: Branch 'default' has more than one head, consider merging
Traceback (most recent call last):
  File "/usr/host/bin/git-remote-hg", line 1348, in <module>
    sys.exit(main(sys.argv))
  File "/usr/host/bin/git-remote-hg", line 1332, in main
    do_import(parser)
  File "/usr/host/bin/git-remote-hg", line 737, in do_import
    export_tag(repo, tag)
  File "/usr/host/bin/git-remote-hg", line 614, in export_tag
    export_ref(repo, tag, 'tags', repo[hgref(tag)])
  File "/usr/x86_64-pc-linux-gnu/lib/python2.7/site-packages/mercurial/localrepo.py", line 856, in __getitem__
    return context.changectx(self, changeid)
  File "/usr/x86_64-pc-linux-gnu/lib/python2.7/site-packages/mercurial/context.py", line 439, in __init__
    (changeid, type(changeid)))
mercurial.error.ProgrammingError: unsupported changeid 'v0.1.0' of type <type 'str'>
fatal: stream ends early
fast-import: dumping crash report to /home/hasufell/git/CM_app/app/3rdparty/webdriver-utils/.git/fast_import_crash_22867
fatal: error while running fast-import
```

**Comment by hasufell** [comment] 2018-09-16 14:29
And that is even after applying https://github.com/felipec/git-remote-hg/issues/72#issuecomment-391079054 which is not part of this repo it seems

**Comment by mnauw** [comment] 2018-09-16 18:12
Even if I say so myself (though others are saying so as well, see e.g. felipec/git-remote-hg#69), this fork is much more maintained and ahead than the the original one.  In particular, the issue reported here is a duplicate of issue #18 which has already been fixed in latest master (and as usual is due to changes in recent Mercurial's internal API).  Note that latest master no longer contains the line as reported in the backtrace (as the problem is in repo[...], which has now been changed).

**Closed as completed by mnauw** 2018-09-16 18:12 UTC
